### ISSUE TITLE
Crash on 3.3.3

### ISSUE THREAD

**Issue by brianmoyano2** [matt-curtis/Sketch-Server#1] opened 2015-07-28 18:11 UTC
Installed this from Sketch Toolbox and sketch crashes when i start the server.

**Comment by matt-curtis** [comment] 2015-07-28 18:16
Thanks for opening an issue. What version of OS X are you running? Which option are you using to start the server?

Also, can you give me the error messages from Sketch in your Utilities/Console.app?

**Comment by brianmoyano2** [comment] 2015-07-28 18:25
I'm on 10.10.2 and both options (Start server and Start server on Port) crashes anyway.
![captura de pantalla 2015-07-28 a las 3 23 40 p m](https://cloud.githubusercontent.com/assets/1211840/8939754/c0d3ecb2-353c-11e5-85bb-3d6ebf5ec787.png)

**Comment by matt-curtis** [comment] 2015-07-28 19:58
I think this might be an issue that arises in the sandboxed version of Sketch. I'm going to construct a debug version.

**Comment by matt-curtis** [comment] 2015-08-02 01:39
Could you download and try the debug version? It won't fix your problem, but it will give me more information on what's going on.

https://github.com/matt-curtis/Sketch-Server/tree/debug

**Comment by brianmoyano2** [comment] 2015-08-02 23:15
Sure. Now i got this sequence of 'alerts boxes' and now the plugin works. Nevertheless i will test this plugin again in my Mac Mini, because now i'm running it in my macbook pro with 10.10.4

PS: And i din't saw anything in the Console app

![captura de pantalla 2015-08-02 a las 20 10 34](https://cloud.githubusercontent.com/assets/1211840/9028529/b8fe2f2e-3952-11e5-9bd3-99f8e53f21be.png)
![captura de pantalla 2015-08-02 a las 20 10 40](https://cloud.githubusercontent.com/assets/1211840/9028527/b8f82494-3952-11e5-9079-825c6cbb9424.png)
![captura de pantalla 2015-08-02 a las 20 10 44](https://cloud.githubusercontent.com/assets/1211840/9028528/b8fb354e-3952-11e5-9e66-c2d7bcee19bd.png)

**Comment by matt-curtis** [comment] 2015-08-02 23:44
Weird that version fixes it, changes were minimal to non-existent. Did you change computers, Sketch versions, etc.?

**Comment by brianmoyano2** [comment] 2015-08-03 13:26
Yes, changed to my macbook pro. Now i will test it in my Mac Mini (The one that i was using when i opened the issue)

1: I click start server
2: Alert: 'Sketch Server. Attempt to start server on provided(?) port: (null) ...'
3: Alert: 'Sketch Server. Started server successfully on port: 17831? No'
4: Alert: 'Sketch Server. Started server successfully on port: 42737? No'
5: Alert: 'Sketch Server. Started server successfully on port: 45273? No'
6: Alert: 'Sketch Server. Started server successfully on port: 39978? No'
7: Alert: 'Sketch Server. Started server successfully on port: 54146? No'
8: Sketch Crashes

![captura de pantalla 2015-08-03 a las 10 20 55 a m](https://cloud.githubusercontent.com/assets/1211840/9038267/6d3e2eaa-39c9-11e5-8084-a7b21f5f4349.png)

**Comment by matt-curtis** [comment] 2015-08-03 13:31
The other machines that you tested it on that didn't have the problem, where they also using the sandboxed (App Store) version of Sketch?

**Comment by brianmoyano2** [comment] 2015-08-04 00:55
Yes, i use sandboxed in everyone. In my MB Pro with 10.10.4 seems to work, but in my Mac Mini with 10.10.2 don't. Will try updating to 10.10.4.

**Comment by matt-curtis** [comment] 2015-08-04 01:06
It's supposed to work on OS X 10.10 and up, so I'm hoping that's not the problem...

**Comment by matt-curtis** [comment] 2015-08-11 02:28
Any updates on this so I can close?

**Comment by brianmoyano2** [comment] 2015-08-11 19:34
In my macbook pro works fine, but it doesn't in my mac mini. Both 10.10.4, both sandboxed sketch 3.3.3.
I share you the log that sketch gives me when it crash:
https://www.dropbox.com/s/biylret3e7liq9k/Skethch%20Log%20%28Sketch%20Server%29?dl=0

**Comment by matt-curtis** [comment] 2015-08-11 19:50
It looks like the error is caused by the server being released from memory too early. However, since this is working fine in every other setup, I'm thinking it's something unique to that machine.

I'll reopen if any possible culprits come to mind, or someone else reports this issue.

**Comment by DINHDUY** [comment] 2015-08-27 12:04
I got the same problem on Mac BookPro Sketch 3.3.3

**Comment by DINHDUY** [comment] 2015-08-27 12:06
OS X Yosemite
Version 10.10.5 (14F27)
MacBook Pro (Retina, 15-inch, Mid 2014)
Processor 2.2 GHz Intel Core i7

**Comment by matt-curtis** [comment] 2015-08-27 16:43
Well, there's goes the hope of this being a rare issue. Can you share your crash log?

**Comment by guerrero** [comment] 2015-10-14 22:13
Same problem here and it crashes Sketch

OS X Yosemite
Version 10.10.4 (14E46)
MacBook Pro (15-inch, early 2011)
Processor 2.2 GHz Intel Core i7
Sketch Version 3.3.3 (12072) Sandboxed

![console log](https://cloud.githubusercontent.com/assets/3751801/10499574/7db71e36-72d1-11e5-9019-4bdf28075db9.png)

**Comment by matt-curtis** [comment] 2015-10-14 22:19
Looking into this, though it may be awhile. Will come along with a few new features and whatnot

**Comment by guerrero** [comment] 2015-10-14 22:33
Great, thanks Matt. Also, it seems weird but sketch-server works in Sketch Beta Version 3.4. Perhaps it can be a problem related with sandboxing

**Comment by cute** [comment] 2015-10-20 05:47
Sketch.app archived-expanded-entitlements.xcent, sketch-server  require com.apple.security.network.server 

https://developer.apple.com/library/ios/documentation/Miscellaneous/Reference/EntitlementKeyReference/Chapters/EnablingAppSandbox.html

`Network socket for listening for incoming connections initiated by other machine`

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>com.apple.developer.ubiquity-container-identifiers</key>
    <array>
        <string>WUGMZZ5K46.com.bohemiancoding.sketch</string>
    </array>
    <key>com.apple.security.app-sandbox</key>
    <true/>
    <key>com.apple.security.application-groups</key>
    <array>
        <string>WUGMZZ5K46.com.bohemiancoding</string>
    </array>
    <key>com.apple.security.files.bookmarks.app-scope</key>
    <true/>
    <key>com.apple.security.files.user-selected.read-write</key>
    <true/>
    <key>com.apple.security.network.client</key>
    <true/>
    <key>com.apple.security.print</key>
    <true/>
</dict>
</plist>
```

**Comment by matt-curtis** [comment] 2015-10-20 11:09
@cute Ah, interesting. So does changing this file - setting the `com.apple.security.network.server` key to `true` - solve the problem?

**Comment by cute** [comment] 2015-10-27 04:24
@matt-curtis no

Sketch 3.4 support `com.apple.security.network.server`.

**Comment by matt-curtis** [comment] 2015-10-27 11:54
Good to hear this works in 3.4 - I haven't tested it there yet.

**Comment by cute** [comment] 2015-10-28 01:18
@matt-curtis 
sketch 3.4 
Artboards can now be previewed in a web browser and shared on the local network

**Comment by matt-curtis** [comment] 2015-10-28 02:11
I'm aware. I may discontinue Sketch Server :)

**Comment by grstreten** [comment] 2015-10-28 12:08
Got the same issue here - been looking everywhere to find a solution to what I want and Sketch Server seems ideal - nightmare that it doesn't work! Working in Sandbox version on 2013 MacBook Pro Retina 15" i7, Sketch is version 3.3.3.

Update: just read up and seen notes about 3.4. I'll check it out but still would love the flexibility of playing with an open source project like this.

**Closed as completed** 2016-02-22 15:20 UTC
